spring:
  application:
    name: Project ISI

  datasource:
    url: jdbc:sqlserver://${DATABASE_IP:localhost}:${DATABASE_PORT:1433};trustServerCertificate=${DOES_SERVER_TRUST_DATABASE_CERTIFICATE:true}
    username: ${DATABASE_USER:sa}
    password: ${DATABASE_PASSWORD:Project_ISI_2024!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
  swagger-ui.path: /swagger-ui.html



